require('packer_init')

require('options')
require('keymaps')
require('autocmds')

require('plugins/nvim-lspconfig')
require('plugins/null-ls')
require('plugins/lsp_lines')
require('plugins/trouble')
-- require('plugins/lspsaga')
require('plugins/noice')
require('plugins/inc-rename')
-- require('plugins/fidget')
require('plugins/lualine')
require('plugins/bufferline')
require('plugins/telescope')
-- require('plugins/vim-hardtime')
require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
require('plugins/nvim-autopairs')
require('plugins/gitsigns')
require('plugins/git-blame')
require('plugins/prettier')
require('plugins/colorizer')
require('plugins/shade')
require('plugins/indent_blankline')
require('plugins/Comment')
require('plugins/nvim-tree')
require('plugins/nvim-surround')
require('plugins/alpha-nvim')
require('plugins/dressing')
-- require('plugins/nvim-lightbulb')
require('plugins/goto-preview')
require('plugins/substitute')
require('plugins/todo-comments')
require('plugins/luasnip')
