require('packer_init')

require('options')
require('keymaps')
require('autocmds')

require('plugins/lualine')
require('plugins/bufferline')
require('plugins/telescope')
require('plugins/vim-hardtime')
require('plugins/nvim-lspconfig')
require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
require('plugins/nvim-autopairs')
require('plugins/gitsigns')
require('plugins/lspsaga')
require('plugins/null-ls')
require('plugins/prettier')
require('plugins/lsp_lines')
require('plugins/colorizer')
require('plugins/shade')
require('plugins/indent_blankline')
require('plugins/Comment')
require('plugins/trouble')
require('plugins/nvim-tree')
require('plugins/nvim-surround')
