#! /bin/sh
xrdb -merge ~/.Xresources

[ -f "$HOME/.zshenv" ] && source "$HOME/.zshenv"

# Set xkeyboard layout
default_xkb_layout=us
xkeyboard_layout="$HOME/.xkeyboard_layout"

if which setxkbmap>/dev/null; then
    if [ -f "$xkeyboard_layout" ]; then
        xkb_layout=$(cat "$xkeyboard_layout") &&\
            [ -n "$xkb_layout" ] && setxkbmap "$xkb_layout"
    else
        echo "$default_xkb_layout" > "$xkeyboard_layout" &&\
            setxkbmap "$default_xkb_layout"
    fi
fi

eval "$(ssh-agent)"
