#! /bin/sh
[ -f "$HOME/.zshenv" ] && source "$HOME/.zshenv"

export GDK_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# Set Yeti Stereo Microphone, Mic volume to 0%
yeti_card_no=$(get-sound-card-number Yeti Stereo Microphone)
if [ -n "$yeti_card_no" ]; then
    amixer -c"$yeti_card_no" set Mic 0%
fi

# Set xkeyboard layout
default_xkb_layout=us
xkeyboard_layout="$HOME/.xkeyboard_layout"

if which setxkbmap>/dev/null; then
    if [ -f "$xkeyboard_layout" ]; then
        xkb_layout=$(cat "$xkeyboard_layout") &&\
            [ -n "$xkb_layout" ] && setxkbmap "$xkb_layout"
    else
        echo "$default_xkb_layout" > "$xkeyboard_layout" &&\
            setxkbmap "$default_xkb_layout"
    fi
fi

eval "$(ssh-agent)"
