function path {
	case ":$PATH:" in
	  *":$1:"*) :;; # already there
	  *) PATH="$1:$PATH";; # or PATH="$PATH:$new_entry"
	esac
}

path opt/cuda/bin
path /usr/local/bin

path $HOME/.local/bin
path $HOME/.bin

path /opt/genymotion/tools

ANDROID_HOME=$HOME/Android/Sdk

if [ -d "$ANDROID_HOME" ]; then
	path $ANDROID_HOME/emulator
	path $ANDROID_HOME/tools
	path $ANDROID_HOME/tools/bin
	path $ANDROID_HOME/platform-tools

	export ANDROID_HOME
fi

export GDK_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1

export PATH
