function path {
	case ":$PATH:" in
	  *":$1:"*) :;; # already there
	  *) PATH="$1:$PATH";; # or PATH="$PATH:$new_entry"
	esac
}

path opt/cuda/bin
path /usr/local/bin

path $HOME/.local/bin
path $HOME/.bin

export PATH

export GDK_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
