export PATH=$HOME/.local/bin:$HOME/.bin:/usr/local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"

if [ $TERM = "linux" ];then
    ZSH_THEME="candy"
else
    ZSH_THEME="bira"
fi

# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git 
  archlinux
  history
  sudo
  systemd
  web-search
  pip
  python
  npm
)

source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"

alias zshconfig="$EDITOR $HOME/.zshrc"
alias zshreload="source $HOME/.zshrc" 
alias i3config="$EDITOR $HOME/.config/i3/config"
alias nvimconfig="$EDITOR $HOME/.config/nvim/init.vim"
alias gdbtui="gdb -tui -q"

neofetch
