if [ $UID = 0 ]; then
    [ -f "$HOME/.zshenv" ] && source "$HOME/.zshenv"
fi

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="candy"

# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"


# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  history
  archlinux
  systemd
  sudo
  git
  pip
  python
  npm
  brew
  #zsh-autocomplete
  zsh-autosuggestions
  rust
)

[ -f "$ZSH/oh-my-zsh.sh" ] && source "$ZSH/oh-my-zsh.sh"

zstyle ':completion:*' rehash true

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=white,bold"

# Quick edit aliases

alias zsh-config="$EDITOR $HOME/.zshrc"
alias i3-config="$EDITOR $CONFIG/i3/config"
alias nvim-config="$EDITOR $CONFIG/nvim/init.vim"
alias polybar-config="$EDITOR $CONFIG/polybar/config"
alias qutebrowser-config="$EDITOR $CONFIG/qutebrowser/config.py"

# Useful command aliases

alias zsh-source="source $HOME/.zshrc"
alias gdb-tui="gdb -tui -q"
alias nvidia-gpu-utilization="watch -n 5 nvidia-smi -a --display=utilization"


# zsh-syntax-highlighting
source "$HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# rbenv
eval "$(rbenv init - zsh)"

# cargo
if [ -f "$HOME/.cargo/env" ]; then
	source "$HOME/.cargo/env"
fi

# editor
EDITOR="vi"

if command_exists "nvim"; then
    EDITOR="nvim"
elif command_exists "vim"; then
    EDITOR="vim"
fi

export EDITOR;

# directories
export CONFIG="$HOME/.config"
export DOTFILES="$HOME/.dotfiles"
